import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // Values
    public static let dimensionValues2 = 4 
    public static let dimensionValues4 = 8 
    public static let dimensionValues6 = 12 
    public static let dimensionValues8 = 16 
    public static let dimensionValues10 = 20 
    public static let dimensionValues12 = 24 
    public static let dimensionValues14 = 28 
    public static let dimensionValues16 = 32 
    public static let dimensionValues0 = 0 
    public static let dimensionValues1 = 2 
    public static let dimensionValues18 = 36 
    public static let dimensionValues20 = 40 
    public static let dimensionValues22 = 44 
    public static let dimensionValues24 = 48 
}