import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // magenta
        public let magentaMagenta50 = Color(.sRGB, red: 254/255, green: 241/255, blue: 249/255, opacity: 1) 
        public let magentaMagenta100 = Color(.sRGB, red: 254/255, green: 229/255, blue: 245/255, opacity: 1) 
        public let magentaMagenta200 = Color(.sRGB, red: 255/255, green: 202/255, blue: 237/255, opacity: 1) 
        public let magentaMagenta300 = Color(.sRGB, red: 255/255, green: 159/255, blue: 219/255, opacity: 1) 
        public let magentaMagenta400 = Color(.sRGB, red: 255/255, green: 99/255, blue: 193/255, opacity: 1) 
        public let magentaMagenta500 = Color(.sRGB, red: 255/255, green: 39/255, blue: 160/255, opacity: 1) 
        public let magentaMagenta600 = Color(.sRGB, red: 240/255, green: 18/255, blue: 132/255, opacity: 1) 
        public let magentaMagenta700 = Color(.sRGB, red: 209/255, green: 5/255, blue: 104/255, opacity: 1) 
        public let magentaMagenta800 = Color(.sRGB, red: 173/255, green: 7/255, blue: 85/255, opacity: 1) 
        public let magentaMagenta900 = Color(.sRGB, red: 143/255, green: 12/255, blue: 74/255, opacity: 1) 
        public let magentaMagenta950 = Color(.sRGB, red: 88/255, green: 0/255, blue: 40/255, opacity: 1) 

        // purple
        public let purplePurple50 = Color(.sRGB, red: 245/255, green: 242/255, blue: 255/255, opacity: 1) 
        public let purplePurple100 = Color(.sRGB, red: 236/255, green: 232/255, blue: 255/255, opacity: 1) 
        public let purplePurple200 = Color(.sRGB, red: 218/255, green: 212/255, blue: 255/255, opacity: 1) 
        public let purplePurple300 = Color(.sRGB, red: 193/255, green: 177/255, blue: 255/255, opacity: 1) 
        public let purplePurple400 = Color(.sRGB, red: 162/255, green: 133/255, blue: 255/255, opacity: 1) 
        public let purplePurple500 = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let purplePurple600 = Color(.sRGB, red: 118/255, green: 48/255, blue: 247/255, opacity: 1) 
        public let purplePurple700 = Color(.sRGB, red: 104/255, green: 30/255, blue: 227/255, opacity: 1) 
        public let purplePurple800 = Color(.sRGB, red: 87/255, green: 24/255, blue: 191/255, opacity: 1) 
        public let purplePurple900 = Color(.sRGB, red: 72/255, green: 22/255, blue: 156/255, opacity: 1) 
        public let purplePurple950 = Color(.sRGB, red: 44/255, green: 11/255, blue: 106/255, opacity: 1) 

        // blue
        public let blueBlue50 = Color(.sRGB, red: 237/255, green: 250/255, blue: 255/255, opacity: 1) 
        public let blueBlue100 = Color(.sRGB, red: 214/255, green: 241/255, blue: 255/255, opacity: 1) 
        public let blueBlue200 = Color(.sRGB, red: 181/255, green: 233/255, blue: 255/255, opacity: 1) 
        public let blueBlue300 = Color(.sRGB, red: 131/255, green: 220/255, blue: 255/255, opacity: 1) 
        public let blueBlue400 = Color(.sRGB, red: 72/255, green: 199/255, blue: 255/255, opacity: 1) 
        public let blueBlue500 = Color(.sRGB, red: 30/255, green: 167/255, blue: 255/255, opacity: 1) 
        public let blueBlue600 = Color(.sRGB, red: 6/255, green: 137/255, blue: 255/255, opacity: 1) 
        public let blueBlue700 = Color(.sRGB, red: 0/255, green: 117/255, blue: 255/255, opacity: 1) 
        public let blueBlue800 = Color(.sRGB, red: 8/255, green: 89/255, blue: 197/255, opacity: 1) 
        public let blueBlue900 = Color(.sRGB, red: 13/255, green: 78/255, blue: 155/255, opacity: 1) 
        public let blueBlue950 = Color(.sRGB, red: 14/255, green: 48/255, blue: 93/255, opacity: 1) 

        // green
        public let greenGreen50 = Color(.sRGB, red: 232/255, green: 255/255, blue: 228/255, opacity: 1) 
        public let greenGreen100 = Color(.sRGB, red: 203/255, green: 255/255, blue: 197/255, opacity: 1) 
        public let greenGreen200 = Color(.sRGB, red: 154/255, green: 255/255, blue: 146/255, opacity: 1) 
        public let greenGreen300 = Color(.sRGB, red: 91/255, green: 255/255, blue: 83/255, opacity: 1) 
        public let greenGreen400 = Color(.sRGB, red: 36/255, green: 251/255, blue: 32/255, opacity: 1) 
        public let greenGreen500 = Color(.sRGB, red: 0/255, green: 221/255, blue: 0/255, opacity: 1) 
        public let greenGreen600 = Color(.sRGB, red: 0/255, green: 181/255, blue: 5/255, opacity: 1) 
        public let greenGreen700 = Color(.sRGB, red: 2/255, green: 137/255, blue: 7/255, opacity: 1) 
        public let greenGreen800 = Color(.sRGB, red: 8/255, green: 108/255, blue: 12/255, opacity: 1) 
        public let greenGreen900 = Color(.sRGB, red: 12/255, green: 91/255, blue: 17/255, opacity: 1) 
        public let greenGreen950 = Color(.sRGB, red: 0/255, green: 51/255, blue: 5/255, opacity: 1) 

        // yellow
        public let yellowYellow50 = Color(.sRGB, red: 255/255, green: 255/255, blue: 231/255, opacity: 1) 
        public let yellowYellow100 = Color(.sRGB, red: 254/255, green: 255/255, blue: 193/255, opacity: 1) 
        public let yellowYellow200 = Color(.sRGB, red: 255/255, green: 253/255, blue: 134/255, opacity: 1) 
        public let yellowYellow300 = Color(.sRGB, red: 255/255, green: 244/255, blue: 65/255, opacity: 1) 
        public let yellowYellow400 = Color(.sRGB, red: 255/255, green: 229/255, blue: 13/255, opacity: 1) 
        public let yellowYellow500 = Color(.sRGB, red: 255/255, green: 214/255, blue: 0/255, opacity: 1) 
        public let yellowYellow600 = Color(.sRGB, red: 209/255, green: 157/255, blue: 0/255, opacity: 1) 
        public let yellowYellow700 = Color(.sRGB, red: 166/255, green: 113/255, blue: 2/255, opacity: 1) 
        public let yellowYellow800 = Color(.sRGB, red: 137/255, green: 87/255, blue: 10/255, opacity: 1) 
        public let yellowYellow900 = Color(.sRGB, red: 116/255, green: 71/255, blue: 15/255, opacity: 1) 
        public let yellowYellow950 = Color(.sRGB, red: 68/255, green: 37/255, blue: 4/255, opacity: 1) 

        // orange
        public let orangeOrange50 = Color(.sRGB, red: 255/255, green: 250/255, blue: 236/255, opacity: 1) 
        public let orangeOrange100 = Color(.sRGB, red: 255/255, green: 243/255, blue: 211/255, opacity: 1) 
        public let orangeOrange200 = Color(.sRGB, red: 255/255, green: 227/255, blue: 165/255, opacity: 1) 
        public let orangeOrange300 = Color(.sRGB, red: 255/255, green: 206/255, blue: 109/255, opacity: 1) 
        public let orangeOrange400 = Color(.sRGB, red: 255/255, green: 173/255, blue: 50/255, opacity: 1) 
        public let orangeOrange500 = Color(.sRGB, red: 255/255, green: 146/255, blue: 10/255, opacity: 1) 
        public let orangeOrange600 = Color(.sRGB, red: 255/255, green: 122/255, blue: 0/255, opacity: 1) 
        public let orangeOrange700 = Color(.sRGB, red: 204/255, green: 88/255, blue: 2/255, opacity: 1) 
        public let orangeOrange800 = Color(.sRGB, red: 161/255, green: 68/255, blue: 11/255, opacity: 1) 
        public let orangeOrange900 = Color(.sRGB, red: 130/255, green: 58/255, blue: 12/255, opacity: 1) 
        public let orangeOrange950 = Color(.sRGB, red: 70/255, green: 27/255, blue: 4/255, opacity: 1) 

        // brown
        public let brownBrown50 = Color(.sRGB, red: 251/255, green: 246/255, blue: 239/255, opacity: 1) 
        public let brownBrown100 = Color(.sRGB, red: 243/255, green: 229/255, blue: 210/255, opacity: 1) 
        public let brownBrown200 = Color(.sRGB, red: 229/255, green: 201/255, blue: 162/255, opacity: 1) 
        public let brownBrown300 = Color(.sRGB, red: 216/255, green: 169/255, blue: 113/255, opacity: 1) 
        public let brownBrown400 = Color(.sRGB, red: 207/255, green: 142/255, blue: 80/255, opacity: 1) 
        public let brownBrown500 = Color(.sRGB, red: 197/255, green: 115/255, blue: 59/255, opacity: 1) 
        public let brownBrown600 = Color(.sRGB, red: 185/255, green: 94/255, blue: 53/255, opacity: 1) 
        public let brownBrown700 = Color(.sRGB, red: 145/255, green: 65/255, blue: 44/255, opacity: 1) 
        public let brownBrown800 = Color(.sRGB, red: 119/255, green: 53/255, blue: 41/255, opacity: 1) 
        public let brownBrown900 = Color(.sRGB, red: 98/255, green: 45/255, blue: 37/255, opacity: 1) 
        public let brownBrown950 = Color(.sRGB, red: 55/255, green: 21/255, blue: 17/255, opacity: 1) 

        // red
        public let redRed50 = Color(.sRGB, red: 255/255, green: 242/255, blue: 241/255, opacity: 1) 
        public let redRed100 = Color(.sRGB, red: 255/255, green: 225/255, blue: 223/255, opacity: 1) 
        public let redRed200 = Color(.sRGB, red: 255/255, green: 200/255, blue: 197/255, opacity: 1) 
        public let redRed300 = Color(.sRGB, red: 255/255, green: 162/255, blue: 157/255, opacity: 1) 
        public let redRed400 = Color(.sRGB, red: 255/255, green: 108/255, blue: 100/255, opacity: 1) 
        public let redRed500 = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let redRed600 = Color(.sRGB, red: 237/255, green: 33/255, blue: 21/255, opacity: 1) 
        public let redRed700 = Color(.sRGB, red: 200/255, green: 23/255, blue: 13/255, opacity: 1) 
        public let redRed800 = Color(.sRGB, red: 165/255, green: 23/255, blue: 15/255, opacity: 1) 
        public let redRed900 = Color(.sRGB, red: 136/255, green: 26/255, blue: 20/255, opacity: 1) 
        public let redRed950 = Color(.sRGB, red: 75/255, green: 8/255, blue: 4/255, opacity: 1) 

        // platinum
        public let platinumPlatinum50 = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let platinumPlatinum100 = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let platinumPlatinum200 = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let platinumPlatinum300 = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let platinumPlatinum400 = Color(.sRGB, red: 148/255, green: 163/255, blue: 184/255, opacity: 1) 
        public let platinumPlatinum500 = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let platinumPlatinum600 = Color(.sRGB, red: 71/255, green: 85/255, blue: 105/255, opacity: 1) 
        public let platinumPlatinum700 = Color(.sRGB, red: 51/255, green: 65/255, blue: 85/255, opacity: 1) 
        public let platinumPlatinum800 = Color(.sRGB, red: 30/255, green: 41/255, blue: 59/255, opacity: 1) 
        public let platinumPlatinum900 = Color(.sRGB, red: 15/255, green: 23/255, blue: 42/255, opacity: 1) 
        public let platinumPlatinum950 = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // grey
        public let greyWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let greyGrey50 = Color(.sRGB, red: 246/255, green: 246/255, blue: 246/255, opacity: 1) 
        public let greyGrey100 = Color(.sRGB, red: 238/255, green: 238/255, blue: 238/255, opacity: 1) 
        public let greyGrey200 = Color(.sRGB, red: 226/255, green: 226/255, blue: 226/255, opacity: 1) 
        public let greyGrey300 = Color(.sRGB, red: 203/255, green: 203/255, blue: 203/255, opacity: 1) 
        public let greyGrey400 = Color(.sRGB, red: 175/255, green: 175/255, blue: 175/255, opacity: 1) 
        public let greyGrey500 = Color(.sRGB, red: 117/255, green: 117/255, blue: 117/255, opacity: 1) 
        public let greyGrey600 = Color(.sRGB, red: 84/255, green: 84/255, blue: 84/255, opacity: 1) 
        public let greyGrey700 = Color(.sRGB, red: 51/255, green: 51/255, blue: 51/255, opacity: 1) 
        public let greyGrey800 = Color(.sRGB, red: 31/255, green: 31/255, blue: 31/255, opacity: 1) 
        public let greyGrey900 = Color(.sRGB, red: 20/255, green: 20/255, blue: 20/255, opacity: 1) 
        public let greyBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
    }
}