import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    public static let Token = Color.TokenColor()
    
    public struct TokenColor {

        // magenta
        public let magenta50 = Color(.sRGB, red: 254/255, green: 241/255, blue: 249/255, opacity: 1) 
        public let magenta100 = Color(.sRGB, red: 254/255, green: 229/255, blue: 245/255, opacity: 1) 
        public let magenta200 = Color(.sRGB, red: 255/255, green: 202/255, blue: 237/255, opacity: 1) 
        public let magenta300 = Color(.sRGB, red: 255/255, green: 159/255, blue: 219/255, opacity: 1) 
        public let magenta400 = Color(.sRGB, red: 255/255, green: 99/255, blue: 193/255, opacity: 1) 
        public let magenta500 = Color(.sRGB, red: 255/255, green: 39/255, blue: 160/255, opacity: 1) 
        public let magenta600 = Color(.sRGB, red: 240/255, green: 18/255, blue: 132/255, opacity: 1) 
        public let magenta700 = Color(.sRGB, red: 209/255, green: 5/255, blue: 104/255, opacity: 1) 
        public let magenta800 = Color(.sRGB, red: 173/255, green: 7/255, blue: 85/255, opacity: 1) 
        public let magenta900 = Color(.sRGB, red: 143/255, green: 12/255, blue: 74/255, opacity: 1) 
        public let magenta950 = Color(.sRGB, red: 88/255, green: 0/255, blue: 40/255, opacity: 1) 

        // purple
        public let purple50 = Color(.sRGB, red: 245/255, green: 242/255, blue: 255/255, opacity: 1) 
        public let purple100 = Color(.sRGB, red: 236/255, green: 232/255, blue: 255/255, opacity: 1) 
        public let purple200 = Color(.sRGB, red: 218/255, green: 212/255, blue: 255/255, opacity: 1) 
        public let purple300 = Color(.sRGB, red: 193/255, green: 177/255, blue: 255/255, opacity: 1) 
        public let purple400 = Color(.sRGB, red: 162/255, green: 133/255, blue: 255/255, opacity: 1) 
        public let purple500 = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let purple600 = Color(.sRGB, red: 118/255, green: 48/255, blue: 247/255, opacity: 1) 
        public let purple700 = Color(.sRGB, red: 104/255, green: 30/255, blue: 227/255, opacity: 1) 
        public let purple800 = Color(.sRGB, red: 87/255, green: 24/255, blue: 191/255, opacity: 1) 
        public let purple900 = Color(.sRGB, red: 72/255, green: 22/255, blue: 156/255, opacity: 1) 
        public let purplePurple950 = Color(.sRGB, red: 44/255, green: 11/255, blue: 106/255, opacity: 1) 

        // blue
        public let blue50 = Color(.sRGB, red: 237/255, green: 250/255, blue: 255/255, opacity: 1) 
        public let blue100 = Color(.sRGB, red: 214/255, green: 241/255, blue: 255/255, opacity: 1) 
        public let blue200 = Color(.sRGB, red: 181/255, green: 233/255, blue: 255/255, opacity: 1) 
        public let blue300 = Color(.sRGB, red: 131/255, green: 220/255, blue: 255/255, opacity: 1) 
        public let blue400 = Color(.sRGB, red: 72/255, green: 199/255, blue: 255/255, opacity: 1) 
        public let blue500 = Color(.sRGB, red: 30/255, green: 167/255, blue: 255/255, opacity: 1) 
        public let blue600 = Color(.sRGB, red: 6/255, green: 137/255, blue: 255/255, opacity: 1) 
        public let blue700 = Color(.sRGB, red: 0/255, green: 117/255, blue: 255/255, opacity: 1) 
        public let blue800 = Color(.sRGB, red: 8/255, green: 89/255, blue: 197/255, opacity: 1) 
        public let blue900 = Color(.sRGB, red: 13/255, green: 78/255, blue: 155/255, opacity: 1) 
        public let blue950 = Color(.sRGB, red: 14/255, green: 48/255, blue: 93/255, opacity: 1) 

        // green
        public let green50 = Color(.sRGB, red: 232/255, green: 255/255, blue: 228/255, opacity: 1) 
        public let green100 = Color(.sRGB, red: 203/255, green: 255/255, blue: 197/255, opacity: 1) 
        public let green200 = Color(.sRGB, red: 154/255, green: 255/255, blue: 146/255, opacity: 1) 
        public let green300 = Color(.sRGB, red: 91/255, green: 255/255, blue: 83/255, opacity: 1) 
        public let green400 = Color(.sRGB, red: 36/255, green: 251/255, blue: 32/255, opacity: 1) 
        public let green500 = Color(.sRGB, red: 0/255, green: 221/255, blue: 0/255, opacity: 1) 
        public let green600 = Color(.sRGB, red: 0/255, green: 181/255, blue: 5/255, opacity: 1) 
        public let green700 = Color(.sRGB, red: 2/255, green: 137/255, blue: 7/255, opacity: 1) 
        public let green800 = Color(.sRGB, red: 8/255, green: 108/255, blue: 12/255, opacity: 1) 
        public let green900 = Color(.sRGB, red: 12/255, green: 91/255, blue: 17/255, opacity: 1) 
        public let green950 = Color(.sRGB, red: 0/255, green: 51/255, blue: 5/255, opacity: 1) 

        // yellow
        public let yellow50 = Color(.sRGB, red: 255/255, green: 255/255, blue: 231/255, opacity: 1) 
        public let yellow100 = Color(.sRGB, red: 254/255, green: 255/255, blue: 193/255, opacity: 1) 
        public let yellow200 = Color(.sRGB, red: 255/255, green: 253/255, blue: 134/255, opacity: 1) 
        public let yellow300 = Color(.sRGB, red: 255/255, green: 244/255, blue: 65/255, opacity: 1) 
        public let yellow400 = Color(.sRGB, red: 255/255, green: 229/255, blue: 13/255, opacity: 1) 
        public let yellow500 = Color(.sRGB, red: 255/255, green: 214/255, blue: 0/255, opacity: 1) 
        public let yellow600 = Color(.sRGB, red: 209/255, green: 157/255, blue: 0/255, opacity: 1) 
        public let yellow700 = Color(.sRGB, red: 166/255, green: 113/255, blue: 2/255, opacity: 1) 
        public let yellow800 = Color(.sRGB, red: 137/255, green: 87/255, blue: 10/255, opacity: 1) 
        public let yellow900 = Color(.sRGB, red: 116/255, green: 71/255, blue: 15/255, opacity: 1) 
        public let yellow950 = Color(.sRGB, red: 68/255, green: 37/255, blue: 4/255, opacity: 1) 

        // orange
        public let orange50 = Color(.sRGB, red: 255/255, green: 250/255, blue: 236/255, opacity: 1) 
        public let orange100 = Color(.sRGB, red: 255/255, green: 243/255, blue: 211/255, opacity: 1) 
        public let orange200 = Color(.sRGB, red: 255/255, green: 227/255, blue: 165/255, opacity: 1) 
        public let orange300 = Color(.sRGB, red: 255/255, green: 206/255, blue: 109/255, opacity: 1) 
        public let orange400 = Color(.sRGB, red: 255/255, green: 173/255, blue: 50/255, opacity: 1) 
        public let orange500 = Color(.sRGB, red: 255/255, green: 146/255, blue: 10/255, opacity: 1) 
        public let orange600 = Color(.sRGB, red: 255/255, green: 122/255, blue: 0/255, opacity: 1) 
        public let orange700 = Color(.sRGB, red: 204/255, green: 88/255, blue: 2/255, opacity: 1) 
        public let orange800 = Color(.sRGB, red: 161/255, green: 68/255, blue: 11/255, opacity: 1) 
        public let orange900 = Color(.sRGB, red: 130/255, green: 58/255, blue: 12/255, opacity: 1) 
        public let orange950 = Color(.sRGB, red: 70/255, green: 27/255, blue: 4/255, opacity: 1) 

        // brown
        public let brown50 = Color(.sRGB, red: 251/255, green: 246/255, blue: 239/255, opacity: 1) 
        public let brown100 = Color(.sRGB, red: 243/255, green: 229/255, blue: 210/255, opacity: 1) 
        public let brown200 = Color(.sRGB, red: 229/255, green: 201/255, blue: 162/255, opacity: 1) 
        public let brown300 = Color(.sRGB, red: 216/255, green: 169/255, blue: 113/255, opacity: 1) 
        public let brown400 = Color(.sRGB, red: 207/255, green: 142/255, blue: 80/255, opacity: 1) 
        public let brown500 = Color(.sRGB, red: 197/255, green: 115/255, blue: 59/255, opacity: 1) 
        public let brown600 = Color(.sRGB, red: 185/255, green: 94/255, blue: 53/255, opacity: 1) 
        public let brown700 = Color(.sRGB, red: 145/255, green: 65/255, blue: 44/255, opacity: 1) 
        public let brown800 = Color(.sRGB, red: 119/255, green: 53/255, blue: 41/255, opacity: 1) 
        public let brown900 = Color(.sRGB, red: 98/255, green: 45/255, blue: 37/255, opacity: 1) 
        public let brown950 = Color(.sRGB, red: 55/255, green: 21/255, blue: 17/255, opacity: 1) 

        // red
        public let red50 = Color(.sRGB, red: 255/255, green: 242/255, blue: 241/255, opacity: 1) 
        public let red100 = Color(.sRGB, red: 255/255, green: 225/255, blue: 223/255, opacity: 1) 
        public let red200 = Color(.sRGB, red: 255/255, green: 200/255, blue: 197/255, opacity: 1) 
        public let red300 = Color(.sRGB, red: 255/255, green: 162/255, blue: 157/255, opacity: 1) 
        public let red400 = Color(.sRGB, red: 255/255, green: 108/255, blue: 100/255, opacity: 1) 
        public let red500 = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let red600 = Color(.sRGB, red: 237/255, green: 33/255, blue: 21/255, opacity: 1) 
        public let red700 = Color(.sRGB, red: 200/255, green: 23/255, blue: 13/255, opacity: 1) 
        public let red800 = Color(.sRGB, red: 165/255, green: 23/255, blue: 15/255, opacity: 1) 
        public let red900 = Color(.sRGB, red: 136/255, green: 26/255, blue: 20/255, opacity: 1) 
        public let red950 = Color(.sRGB, red: 75/255, green: 8/255, blue: 4/255, opacity: 1) 

        // platinum
        public let platinum50 = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let platinum100 = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let platinum200 = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let platinum300 = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let platinum400 = Color(.sRGB, red: 148/255, green: 163/255, blue: 184/255, opacity: 1) 
        public let platinum500 = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let platinum600 = Color(.sRGB, red: 71/255, green: 85/255, blue: 105/255, opacity: 1) 
        public let platinum700 = Color(.sRGB, red: 51/255, green: 65/255, blue: 85/255, opacity: 1) 
        public let platinum800 = Color(.sRGB, red: 30/255, green: 41/255, blue: 59/255, opacity: 1) 
        public let platinum900 = Color(.sRGB, red: 15/255, green: 23/255, blue: 42/255, opacity: 1) 
        public let platinum950 = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // grey
        public let greyWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let grey50 = Color(.sRGB, red: 246/255, green: 246/255, blue: 246/255, opacity: 1) 
        public let grey100 = Color(.sRGB, red: 238/255, green: 238/255, blue: 238/255, opacity: 1) 
        public let grey200 = Color(.sRGB, red: 226/255, green: 226/255, blue: 226/255, opacity: 1) 
        public let grey300 = Color(.sRGB, red: 203/255, green: 203/255, blue: 203/255, opacity: 1) 
        public let grey400 = Color(.sRGB, red: 175/255, green: 175/255, blue: 175/255, opacity: 1) 
        public let grey500 = Color(.sRGB, red: 117/255, green: 117/255, blue: 117/255, opacity: 1) 
        public let grey600 = Color(.sRGB, red: 84/255, green: 84/255, blue: 84/255, opacity: 1) 
        public let grey700 = Color(.sRGB, red: 51/255, green: 51/255, blue: 51/255, opacity: 1) 
        public let grey800 = Color(.sRGB, red: 31/255, green: 31/255, blue: 31/255, opacity: 1) 
        public let grey900 = Color(.sRGB, red: 20/255, green: 20/255, blue: 20/255, opacity: 1) 
        public let greyBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
    }
    
    
}
