import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    // M3

    // label

    func textStyleM3LabelLarge() -> some View {
        return self
            .font(Font.custom("Roboto-500", size: 14))
    }

    // body

    func textStyleM3BodyLarge() -> some View {
        return self
            .font(Font.custom("Roboto-400", size: 16))
    }

    // Title2

    func textStyleTitle2Regular() -> some View {
        return self
            .font(Font.custom("SF Pro Display-400", size: 22))
    }

    // Callout

    func textStyleCalloutRegular() -> some View {
        return self
            .font(Font.custom("SF Pro Display-400", size: 16))
    }

    // Typography

    // 6

    func textStyleTypography6Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 24))
    }

    func textStyleTypography6Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 24))
    }

    func textStyleTypography6Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 24))
    }

    func textStyleTypography6Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 24))
    }

    // 2

    func textStyleTypography2Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 14))
    }

    func textStyleTypography2Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 14))
    }

    func textStyleTypography2Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 14))
    }

    func textStyleTypography2Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 14))
    }

    // 1

    func textStyleTypography1Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 12))
    }

    func textStyleTypography1Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 12))
    }

    func textStyleTypography1Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 12))
    }

    func textStyleTypography1Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 12))
    }

    // 5

    func textStyleTypography5Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 20))
    }

    func textStyleTypography5Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 20))
    }

    func textStyleTypography5Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 20))
    }

    func textStyleTypography5Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 20))
    }

    // 4

    func textStyleTypography4Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 18))
    }

    func textStyleTypography4Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 18))
    }

    func textStyleTypography4Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 18))
    }

    func textStyleTypography4Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 18))
    }

    // 7

    func textStyleTypography7Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 28))
    }

    func textStyleTypography7Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 28))
    }

    func textStyleTypography7Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 28))
    }

    func textStyleTypography7Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 28))
    }

    // 8

    func textStyleTypography8Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 35))
    }

    func textStyleTypography8Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 35))
    }

    func textStyleTypography8Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 35))
    }

    func textStyleTypography8Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 35))
    }

    // 9

    func textStyleTypography9Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 60))
    }

    func textStyleTypography9Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 60))
    }

    func textStyleTypography9Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 60))
    }

    func textStyleTypography9Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 60))
    }

    // 3

    func textStyleTypography3Bold() -> some View {
        return self
            .font(Font.custom("Inter-700", size: 16))
    }

    func textStyleTypography3Regular() -> some View {
        return self
            .font(Font.custom("Inter-400", size: 16))
    }

    func textStyleTypography3Light() -> some View {
        return self
            .font(Font.custom("Inter-300", size: 16))
    }

    func textStyleTypography3Medium() -> some View {
        return self
            .font(Font.custom("Inter-500", size: 16))
    }

    // Body

    func textStyleBodyRegular() -> some View {
        return self
            .font(Font.custom("SF Pro Text-400", size: 17))
    }

    func textStyleBodyBold() -> some View {
        return self
            .font(Font.custom("SF Pro Text-600", size: 17))
    }

    // Footnote

    func textStyleFootnoteBold() -> some View {
        return self
            .font(Font.custom("SF Pro Text-600", size: 13))
    }
}
