import SwiftUI

// Generated by Supernova - do not modify manually
@available(iOS 13.0, *)
public extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {
    }
}
