import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension
    public static let dimensionWidth = 320 
    public static let dimensionHeight = 568 
    public static let dimension0 = 0 
    public static let dimension05 = 2 
    public static let dimension1 = 4 
    public static let dimension2 = 8 
    public static let dimension3 = 12 
    public static let dimension4 = 16 
    public static let dimension5 = 20 
    public static let dimension6 = 24 
    public static let dimension7 = 28 
    public static let dimension8 = 32 
    public static let dimension9 = 36 
    public static let dimension10 = 40 
    public static let dimension11 = 44 
    public static let dimension12 = 48 
    public static let dimension14 = 56 
    public static let dimension16 = 64 
    public static let dimension20 = 80 
    public static let dimension24 = 96 

    // None
    public static let dimensionNone1 = 0 
    public static let dimensionNone1Max = 0 
    public static let dimensionNone2 = 0 
    public static let dimensionNone2Max = 0 
    public static let dimensionNone3 = 0 
    public static let dimensionNone3Max = 0 
    public static let dimensionNone4 = 0 
    public static let dimensionNone4Max = 0 
    public static let dimensionNone5 = 0 
    public static let dimensionNone5Max = 0 
    public static let dimensionNone6 = 0 
    public static let dimensionNone6Max = 0 

    // Small
    public static let dimensionSmall1 = 1.5 
    public static let dimensionSmall1Max = 1.5 
    public static let dimensionSmall2 = 2 
    public static let dimensionSmall2Max = 2 
    public static let dimensionSmall3 = 3 
    public static let dimensionSmall3Max = 3 
    public static let dimensionSmall4 = 4 
    public static let dimensionSmall4Max = 4 
    public static let dimensionSmall5 = 6 
    public static let dimensionSmall5Max = 6 
    public static let dimensionSmall6 = 8 
    public static let dimensionSmall6Max = 8 

    // Medium
    public static let dimensionMedium1 = 3 
    public static let dimensionMedium1Max = 3 
    public static let dimensionMedium2 = 4 
    public static let dimensionMedium2Max = 4 
    public static let dimensionMedium3 = 6 
    public static let dimensionMedium3Max = 6 
    public static let dimensionMedium4 = 8 
    public static let dimensionMedium4Max = 8 
    public static let dimensionMedium5 = 12 
    public static let dimensionMedium5Max = 12 
    public static let dimensionMedium6 = 16 
    public static let dimensionMedium6Max = 16 

    // Large
    public static let dimensionLarge1 = 4.5 
    public static let dimensionLarge1Max = 4.5 
    public static let dimensionLarge2 = 6 
    public static let dimensionLarge2Max = 6 
    public static let dimensionLarge3 = 9 
    public static let dimensionLarge3Max = 9 
    public static let dimensionLarge4 = 12 
    public static let dimensionLarge4Max = 12 
    public static let dimensionLarge5 = 18 
    public static let dimensionLarge5Max = 18 
    public static let dimensionLarge6 = 24 
    public static let dimensionLarge6Max = 24 

    // Full
    public static let dimensionFull1 = 6 
    public static let dimensionFull1Max = 9999 
    public static let dimensionFull2 = 8 
    public static let dimensionFull2Max = 9999 
    public static let dimensionFull3 = 12 
    public static let dimensionFull3Max = 9999 
    public static let dimensionFull4 = 16 
    public static let dimensionFull4Max = 9999 
    public static let dimensionFull5 = 24 
    public static let dimensionFull5Max = 9999 
    public static let dimensionFull6 = 32 
    public static let dimensionFull6Max = 9999 
}