import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // color

        // magenta
        public let colormagentaMagenta50 = Color(.sRGB, red: 254/255, green: 241/255, blue: 249/255, opacity: 1) 
        public let colormagentaMagenta100 = Color(.sRGB, red: 254/255, green: 229/255, blue: 245/255, opacity: 1) 
        public let colormagentaMagenta200 = Color(.sRGB, red: 255/255, green: 202/255, blue: 237/255, opacity: 1) 
        public let colormagentaMagenta300 = Color(.sRGB, red: 255/255, green: 159/255, blue: 219/255, opacity: 1) 
        public let colormagentaMagenta400 = Color(.sRGB, red: 255/255, green: 99/255, blue: 193/255, opacity: 1) 
        public let colormagentaMagenta500 = Color(.sRGB, red: 255/255, green: 39/255, blue: 160/255, opacity: 1) 
        public let colormagentaMagenta600 = Color(.sRGB, red: 240/255, green: 18/255, blue: 132/255, opacity: 1) 
        public let colormagentaMagenta700 = Color(.sRGB, red: 209/255, green: 5/255, blue: 104/255, opacity: 1) 
        public let colormagentaMagenta800 = Color(.sRGB, red: 173/255, green: 7/255, blue: 85/255, opacity: 1) 
        public let colormagentaMagenta900 = Color(.sRGB, red: 143/255, green: 12/255, blue: 74/255, opacity: 1) 
        public let colormagentaMagenta950 = Color(.sRGB, red: 88/255, green: 0/255, blue: 40/255, opacity: 1) 

        // purple
        public let colorpurplePurple50 = Color(.sRGB, red: 245/255, green: 242/255, blue: 255/255, opacity: 1) 
        public let colorpurplePurple100 = Color(.sRGB, red: 236/255, green: 232/255, blue: 255/255, opacity: 1) 
        public let colorpurplePurple200 = Color(.sRGB, red: 218/255, green: 212/255, blue: 255/255, opacity: 1) 
        public let colorpurplePurple300 = Color(.sRGB, red: 193/255, green: 177/255, blue: 255/255, opacity: 1) 
        public let colorpurplePurple400 = Color(.sRGB, red: 162/255, green: 133/255, blue: 255/255, opacity: 1) 
        public let colorpurplePurple500 = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let colorpurplePurple600 = Color(.sRGB, red: 118/255, green: 48/255, blue: 247/255, opacity: 1) 
        public let colorpurplePurple700 = Color(.sRGB, red: 104/255, green: 30/255, blue: 227/255, opacity: 1) 
        public let colorpurplePurple800 = Color(.sRGB, red: 87/255, green: 24/255, blue: 191/255, opacity: 1) 
        public let colorpurplePurple900 = Color(.sRGB, red: 72/255, green: 22/255, blue: 156/255, opacity: 1) 
        public let colorpurplePurple950 = Color(.sRGB, red: 44/255, green: 11/255, blue: 106/255, opacity: 1) 

        // blue
        public let colorblueBlue50 = Color(.sRGB, red: 237/255, green: 250/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue100 = Color(.sRGB, red: 214/255, green: 241/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue200 = Color(.sRGB, red: 181/255, green: 233/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue300 = Color(.sRGB, red: 131/255, green: 220/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue400 = Color(.sRGB, red: 72/255, green: 199/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue500 = Color(.sRGB, red: 30/255, green: 167/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue600 = Color(.sRGB, red: 6/255, green: 137/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue700 = Color(.sRGB, red: 0/255, green: 117/255, blue: 255/255, opacity: 1) 
        public let colorblueBlue800 = Color(.sRGB, red: 8/255, green: 89/255, blue: 197/255, opacity: 1) 
        public let colorblueBlue900 = Color(.sRGB, red: 13/255, green: 78/255, blue: 155/255, opacity: 1) 
        public let colorblueBlue950 = Color(.sRGB, red: 14/255, green: 48/255, blue: 93/255, opacity: 1) 

        // green
        public let colorgreenGreen50 = Color(.sRGB, red: 232/255, green: 255/255, blue: 228/255, opacity: 1) 
        public let colorgreenGreen100 = Color(.sRGB, red: 203/255, green: 255/255, blue: 197/255, opacity: 1) 
        public let colorgreenGreen200 = Color(.sRGB, red: 154/255, green: 255/255, blue: 146/255, opacity: 1) 
        public let colorgreenGreen300 = Color(.sRGB, red: 91/255, green: 255/255, blue: 83/255, opacity: 1) 
        public let colorgreenGreen400 = Color(.sRGB, red: 36/255, green: 251/255, blue: 32/255, opacity: 1) 
        public let colorgreenGreen500 = Color(.sRGB, red: 0/255, green: 221/255, blue: 0/255, opacity: 1) 
        public let colorgreenGreen600 = Color(.sRGB, red: 0/255, green: 181/255, blue: 5/255, opacity: 1) 
        public let colorgreenGreen700 = Color(.sRGB, red: 2/255, green: 137/255, blue: 7/255, opacity: 1) 
        public let colorgreenGreen800 = Color(.sRGB, red: 8/255, green: 108/255, blue: 12/255, opacity: 1) 
        public let colorgreenGreen900 = Color(.sRGB, red: 12/255, green: 91/255, blue: 17/255, opacity: 1) 
        public let colorgreenGreen950 = Color(.sRGB, red: 0/255, green: 51/255, blue: 5/255, opacity: 1) 

        // yellow
        public let coloryellowYellow50 = Color(.sRGB, red: 255/255, green: 255/255, blue: 231/255, opacity: 1) 
        public let coloryellowYellow100 = Color(.sRGB, red: 254/255, green: 255/255, blue: 193/255, opacity: 1) 
        public let coloryellowYellow200 = Color(.sRGB, red: 255/255, green: 253/255, blue: 134/255, opacity: 1) 
        public let coloryellowYellow300 = Color(.sRGB, red: 255/255, green: 244/255, blue: 65/255, opacity: 1) 
        public let coloryellowYellow400 = Color(.sRGB, red: 255/255, green: 229/255, blue: 13/255, opacity: 1) 
        public let coloryellowYellow500 = Color(.sRGB, red: 255/255, green: 214/255, blue: 0/255, opacity: 1) 
        public let coloryellowYellow600 = Color(.sRGB, red: 209/255, green: 157/255, blue: 0/255, opacity: 1) 
        public let coloryellowYellow700 = Color(.sRGB, red: 166/255, green: 113/255, blue: 2/255, opacity: 1) 
        public let coloryellowYellow800 = Color(.sRGB, red: 137/255, green: 87/255, blue: 10/255, opacity: 1) 
        public let coloryellowYellow900 = Color(.sRGB, red: 116/255, green: 71/255, blue: 15/255, opacity: 1) 
        public let coloryellowYellow950 = Color(.sRGB, red: 68/255, green: 37/255, blue: 4/255, opacity: 1) 

        // orange
        public let colororangeOrange50 = Color(.sRGB, red: 255/255, green: 250/255, blue: 236/255, opacity: 1) 
        public let colororangeOrange100 = Color(.sRGB, red: 255/255, green: 243/255, blue: 211/255, opacity: 1) 
        public let colororangeOrange200 = Color(.sRGB, red: 255/255, green: 227/255, blue: 165/255, opacity: 1) 
        public let colororangeOrange300 = Color(.sRGB, red: 255/255, green: 206/255, blue: 109/255, opacity: 1) 
        public let colororangeOrange400 = Color(.sRGB, red: 255/255, green: 173/255, blue: 50/255, opacity: 1) 
        public let colororangeOrange500 = Color(.sRGB, red: 255/255, green: 146/255, blue: 10/255, opacity: 1) 
        public let colororangeOrange600 = Color(.sRGB, red: 255/255, green: 122/255, blue: 0/255, opacity: 1) 
        public let colororangeOrange700 = Color(.sRGB, red: 204/255, green: 88/255, blue: 2/255, opacity: 1) 
        public let colororangeOrange800 = Color(.sRGB, red: 161/255, green: 68/255, blue: 11/255, opacity: 1) 
        public let colororangeOrange900 = Color(.sRGB, red: 130/255, green: 58/255, blue: 12/255, opacity: 1) 
        public let colororangeOrange950 = Color(.sRGB, red: 70/255, green: 27/255, blue: 4/255, opacity: 1) 

        // red
        public let colorredRed50 = Color(.sRGB, red: 255/255, green: 242/255, blue: 241/255, opacity: 1) 
        public let colorredRed100 = Color(.sRGB, red: 255/255, green: 225/255, blue: 223/255, opacity: 1) 
        public let colorredRed200 = Color(.sRGB, red: 255/255, green: 200/255, blue: 197/255, opacity: 1) 
        public let colorredRed300 = Color(.sRGB, red: 255/255, green: 162/255, blue: 157/255, opacity: 1) 
        public let colorredRed400 = Color(.sRGB, red: 255/255, green: 108/255, blue: 100/255, opacity: 1) 
        public let colorredRed500 = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let colorredRed600 = Color(.sRGB, red: 237/255, green: 33/255, blue: 21/255, opacity: 1) 
        public let colorredRed700 = Color(.sRGB, red: 200/255, green: 23/255, blue: 13/255, opacity: 1) 
        public let colorredRed800 = Color(.sRGB, red: 165/255, green: 23/255, blue: 15/255, opacity: 1) 
        public let colorredRed900 = Color(.sRGB, red: 136/255, green: 26/255, blue: 20/255, opacity: 1) 
        public let colorredRed950 = Color(.sRGB, red: 75/255, green: 8/255, blue: 4/255, opacity: 1) 

        // brown
        public let colorbrownBrown50 = Color(.sRGB, red: 251/255, green: 246/255, blue: 239/255, opacity: 1) 
        public let colorbrownBrown100 = Color(.sRGB, red: 243/255, green: 229/255, blue: 210/255, opacity: 1) 
        public let colorbrownBrown200 = Color(.sRGB, red: 229/255, green: 201/255, blue: 162/255, opacity: 1) 
        public let colorbrownBrown300 = Color(.sRGB, red: 216/255, green: 169/255, blue: 113/255, opacity: 1) 
        public let colorbrownBrown400 = Color(.sRGB, red: 207/255, green: 142/255, blue: 80/255, opacity: 1) 
        public let colorbrownBrown500 = Color(.sRGB, red: 197/255, green: 115/255, blue: 59/255, opacity: 1) 
        public let colorbrownBrown600 = Color(.sRGB, red: 185/255, green: 94/255, blue: 53/255, opacity: 1) 
        public let colorbrownBrown700 = Color(.sRGB, red: 145/255, green: 65/255, blue: 44/255, opacity: 1) 
        public let colorbrownBrown800 = Color(.sRGB, red: 119/255, green: 53/255, blue: 41/255, opacity: 1) 
        public let colorbrownBrown900 = Color(.sRGB, red: 98/255, green: 45/255, blue: 37/255, opacity: 1) 
        public let colorbrownBrown950 = Color(.sRGB, red: 55/255, green: 21/255, blue: 17/255, opacity: 1) 

        // platinum
        public let colorplatinumPlatinum50 = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let colorplatinumPlatinum100 = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let colorplatinumPlatinum200 = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let colorplatinumPlatinum300 = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let colorplatinumPlatinum400 = Color(.sRGB, red: 148/255, green: 163/255, blue: 184/255, opacity: 1) 
        public let colorplatinumPlatinum500 = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let colorplatinumPlatinum600 = Color(.sRGB, red: 71/255, green: 85/255, blue: 105/255, opacity: 1) 
        public let colorplatinumPlatinum700 = Color(.sRGB, red: 51/255, green: 65/255, blue: 85/255, opacity: 1) 
        public let colorplatinumPlatinum800 = Color(.sRGB, red: 30/255, green: 41/255, blue: 59/255, opacity: 1) 
        public let colorplatinumPlatinum900 = Color(.sRGB, red: 15/255, green: 23/255, blue: 42/255, opacity: 1) 
        public let colorplatinumPlatinum950 = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // grey
        public let colorgreyWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorgreyGrey50 = Color(.sRGB, red: 246/255, green: 246/255, blue: 246/255, opacity: 1) 
        public let colorgreyGrey100 = Color(.sRGB, red: 238/255, green: 238/255, blue: 238/255, opacity: 1) 
        public let colorgreyGrey200 = Color(.sRGB, red: 226/255, green: 226/255, blue: 226/255, opacity: 1) 
        public let colorgreyGrey300 = Color(.sRGB, red: 203/255, green: 203/255, blue: 203/255, opacity: 1) 
        public let colorgreyGrey400 = Color(.sRGB, red: 175/255, green: 175/255, blue: 175/255, opacity: 1) 
        public let colorgreyGrey500 = Color(.sRGB, red: 117/255, green: 117/255, blue: 117/255, opacity: 1) 
        public let colorgreyGrey600 = Color(.sRGB, red: 84/255, green: 84/255, blue: 84/255, opacity: 1) 
        public let colorgreyGrey700 = Color(.sRGB, red: 51/255, green: 51/255, blue: 51/255, opacity: 1) 
        public let colorgreyGrey800 = Color(.sRGB, red: 31/255, green: 31/255, blue: 31/255, opacity: 1) 
        public let colorgreyGrey900 = Color(.sRGB, red: 20/255, green: 20/255, blue: 20/255, opacity: 1) 
        public let colorgreyBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 

        // toggle
        public let toggleToggleBackgroundColor = Color(.sRGB, red: 226/255, green: 226/255, blue: 226/255, opacity: 1) 
        public let toggleToggleDotColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let toggleToggleActiveBackgroundColor = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 

        // chip
        public let chipChipBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let chipChipTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let chipChipBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let chipChipAmountColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let chipChipActiveBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let chipChipActiveBackgroundColor = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let chipChipActiveAmountColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let chipChipIconColor = Color(.sRGB, red: 51/255, green: 65/255, blue: 85/255, opacity: 1) 

        // tab control
        public let tabControlTabControlBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let tabControlTabControlSelectColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let tabControlTabControlBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let tabControlTabControlNotSelectColor = Color(.sRGB, red: 148/255, green: 163/255, blue: 184/255, opacity: 1) 

        // segmented control
        public let segmentedControlSegmentedControlBackgroundColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let segmentedControlSegmentedControlTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let segmentedControlSegmentedControlActiveColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // avatar
        public let avatarAvatarBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let avatarAvatarBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let avatarAvatarActiveColor = Color(.sRGB, red: 0/255, green: 221/255, blue: 0/255, opacity: 1) 
        public let avatarAvatarIconColor = Color(.sRGB, red: 51/255, green: 65/255, blue: 85/255, opacity: 1) 

        // top navigation
        public let topNavigationNavigationBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let topNavigationNavigationTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let topNavigationNavigationIconColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let topNavigationNavigationModalColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let topNavigationNavigationModal2Color = Color(.sRGB, red: 217/255, green: 217/255, blue: 217/255, opacity: 1) 

        // loading
        public let loadingColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let loadingColor2 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // message
        public let messageMessageOwnBackgroundColor = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let messageMessageOwnTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let messageMessageOwnSubtextColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let messageMessageForeignBackgroundColor = Color(.sRGB, red: 30/255, green: 41/255, blue: 59/255, opacity: 1) 
        public let messageMessageForeignSubtextColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let messageMessageForeignTextColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // line item
        public let lineItemLineItemIconColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let lineItemLineItemTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let lineItemLineItemSubtextColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let lineItemLineItemBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // notification
        public let notificationNotificationErrorBackgroundColor = Color(.sRGB, red: 255/255, green: 242/255, blue: 241/255, opacity: 1) 
        public let notificationNotificationErrorIconColor = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let notificationNotificationSuccessBackgroundColor = Color(.sRGB, red: 232/255, green: 255/255, blue: 228/255, opacity: 1) 
        public let notificationNotificationSuccessIconColor = Color(.sRGB, red: 0/255, green: 221/255, blue: 0/255, opacity: 1) 
        public let notificationNotificationWarningBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 231/255, opacity: 1) 
        public let notificationNotificationWarningIconColor = Color(.sRGB, red: 255/255, green: 214/255, blue: 0/255, opacity: 1) 
        public let notificationNotificationInfoBackgroundColor = Color(.sRGB, red: 245/255, green: 242/255, blue: 255/255, opacity: 1) 
        public let notificationNotificationInfoIconColor = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let notificationNotificationTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let notificationNotificationIconColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // tooltip
        public let tooltipTooltipBackgroundColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let tooltipTooltipTextColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // card
        public let cardCardTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let cardCardSubtitleColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let cardCardBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let cardCardBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // ios color

        // light
        public let iosColorlightRed = Color(.sRGB, red: 255/255, green: 59/255, blue: 48/255, opacity: 1) 
        public let iosColorlightOrange = Color(.sRGB, red: 255/255, green: 149/255, blue: 0/255, opacity: 1) 
        public let iosColorlightYellow = Color(.sRGB, red: 255/255, green: 204/255, blue: 0/255, opacity: 1) 
        public let iosColorlightGreen = Color(.sRGB, red: 52/255, green: 199/255, blue: 89/255, opacity: 1) 
        public let iosColorlightTeal = Color(.sRGB, red: 90/255, green: 200/255, blue: 250/255, opacity: 1) 
        public let iosColorlightBlue = Color(.sRGB, red: 0/255, green: 122/255, blue: 255/255, opacity: 1) 
        public let iosColorlightIndigo = Color(.sRGB, red: 88/255, green: 86/255, blue: 214/255, opacity: 1) 
        public let iosColorlightPurple = Color(.sRGB, red: 175/255, green: 82/255, blue: 222/255, opacity: 1) 
        public let iosColorlightPink = Color(.sRGB, red: 255/255, green: 45/255, blue: 85/255, opacity: 1) 
        public let iosColorlightGray = Color(.sRGB, red: 142/255, green: 142/255, blue: 147/255, opacity: 1) 
        public let iosColorlightGray200 = Color(.sRGB, red: 174/255, green: 174/255, blue: 178/255, opacity: 1) 
        public let iosColorlightGray300 = Color(.sRGB, red: 199/255, green: 199/255, blue: 204/255, opacity: 1) 
        public let iosColorlightGray400 = Color(.sRGB, red: 209/255, green: 209/255, blue: 214/255, opacity: 1) 
        public let iosColorlightGray500 = Color(.sRGB, red: 229/255, green: 229/255, blue: 234/255, opacity: 1) 
        public let iosColorlightGray600 = Color(.sRGB, red: 242/255, green: 242/255, blue: 247/255, opacity: 1) 
        public let iosColorlightBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosColorlightWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // dark
        public let iosColordarkRed = Color(.sRGB, red: 255/255, green: 69/255, blue: 58/255, opacity: 1) 
        public let iosColordarkOrange = Color(.sRGB, red: 255/255, green: 159/255, blue: 10/255, opacity: 1) 
        public let iosColordarkYellow = Color(.sRGB, red: 255/255, green: 214/255, blue: 10/255, opacity: 1) 
        public let iosColordarkGreen = Color(.sRGB, red: 48/255, green: 209/255, blue: 88/255, opacity: 1) 
        public let iosColordarkTeal = Color(.sRGB, red: 100/255, green: 210/255, blue: 255/255, opacity: 1) 
        public let iosColordarkBlue = Color(.sRGB, red: 10/255, green: 132/255, blue: 255/255, opacity: 1) 
        public let iosColordarkIndigo = Color(.sRGB, red: 94/255, green: 92/255, blue: 230/255, opacity: 1) 
        public let iosColordarkPurple = Color(.sRGB, red: 191/255, green: 90/255, blue: 242/255, opacity: 1) 
        public let iosColordarkPink = Color(.sRGB, red: 255/255, green: 45/255, blue: 85/255, opacity: 1) 
        public let iosColordarkGray = Color(.sRGB, red: 142/255, green: 142/255, blue: 147/255, opacity: 1) 
        public let iosColordarkGray200 = Color(.sRGB, red: 99/255, green: 99/255, blue: 102/255, opacity: 1) 
        public let iosColordarkGray300 = Color(.sRGB, red: 72/255, green: 72/255, blue: 74/255, opacity: 1) 
        public let iosColordarkGray400 = Color(.sRGB, red: 58/255, green: 58/255, blue: 60/255, opacity: 1) 
        public let iosColordarkGray500 = Color(.sRGB, red: 44/255, green: 44/255, blue: 46/255, opacity: 1) 
        public let iosColordarkGray600 = Color(.sRGB, red: 28/255, green: 28/255, blue: 30/255, opacity: 1) 
        public let iosColordarkBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosColordarkWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // android color

        // teal
        public let androidColortealTeal900 = Color(.sRGB, red: 0/255, green: 77/255, blue: 64/255, opacity: 1) 
        public let androidColortealTeal800 = Color(.sRGB, red: 0/255, green: 105/255, blue: 92/255, opacity: 1) 
        public let androidColortealTeal700 = Color(.sRGB, red: 0/255, green: 121/255, blue: 107/255, opacity: 1) 
        public let androidColortealTeal600 = Color(.sRGB, red: 0/255, green: 137/255, blue: 123/255, opacity: 1) 
        public let androidColortealTeal500 = Color(.sRGB, red: 0/255, green: 150/255, blue: 136/255, opacity: 1) 
        public let androidColortealTeal400 = Color(.sRGB, red: 38/255, green: 166/255, blue: 154/255, opacity: 1) 
        public let androidColortealTeal300 = Color(.sRGB, red: 77/255, green: 182/255, blue: 172/255, opacity: 1) 
        public let androidColortealTeal200 = Color(.sRGB, red: 128/255, green: 203/255, blue: 196/255, opacity: 1) 
        public let androidColortealTeal100 = Color(.sRGB, red: 178/255, green: 223/255, blue: 219/255, opacity: 1) 
        public let androidColortealTeal50 = Color(.sRGB, red: 224/255, green: 242/255, blue: 241/255, opacity: 1) 

        // light blue
        public let androidColorlightBlueLightBlue900 = Color(.sRGB, red: 1/255, green: 87/255, blue: 155/255, opacity: 1) 
        public let androidColorlightBlueLightBlue800 = Color(.sRGB, red: 2/255, green: 119/255, blue: 189/255, opacity: 1) 
        public let androidColorlightBlueLightBlue700 = Color(.sRGB, red: 2/255, green: 136/255, blue: 209/255, opacity: 1) 
        public let androidColorlightBlueLightBlue600 = Color(.sRGB, red: 3/255, green: 155/255, blue: 229/255, opacity: 1) 
        public let androidColorlightBlueLightBlue500 = Color(.sRGB, red: 3/255, green: 169/255, blue: 244/255, opacity: 1) 
        public let androidColorlightBlueLightBlue400 = Color(.sRGB, red: 41/255, green: 182/255, blue: 246/255, opacity: 1) 
        public let androidColorlightBlueLightBlue300 = Color(.sRGB, red: 79/255, green: 195/255, blue: 247/255, opacity: 1) 
        public let androidColorlightBlueLightBlue200 = Color(.sRGB, red: 129/255, green: 212/255, blue: 250/255, opacity: 1) 
        public let androidColorlightBlueLightBlue100 = Color(.sRGB, red: 179/255, green: 229/255, blue: 252/255, opacity: 1) 
        public let androidColorlightBlueLightBlue50 = Color(.sRGB, red: 225/255, green: 245/255, blue: 254/255, opacity: 1) 

        // lime
        public let androidColorlimeLime900 = Color(.sRGB, red: 130/255, green: 119/255, blue: 23/255, opacity: 1) 
        public let androidColorlimeLime800 = Color(.sRGB, red: 158/255, green: 157/255, blue: 36/255, opacity: 1) 
        public let androidColorlimeLime700 = Color(.sRGB, red: 175/255, green: 180/255, blue: 43/255, opacity: 1) 
        public let androidColorlimeLime600 = Color(.sRGB, red: 192/255, green: 202/255, blue: 51/255, opacity: 1) 
        public let androidColorlimeLime500 = Color(.sRGB, red: 205/255, green: 220/255, blue: 57/255, opacity: 1) 
        public let androidColorlimeLime400 = Color(.sRGB, red: 212/255, green: 225/255, blue: 87/255, opacity: 1) 
        public let androidColorlimeLime300 = Color(.sRGB, red: 220/255, green: 231/255, blue: 117/255, opacity: 1) 
        public let androidColorlimeLime200 = Color(.sRGB, red: 230/255, green: 238/255, blue: 156/255, opacity: 1) 
        public let androidColorlimeLime100 = Color(.sRGB, red: 240/255, green: 244/255, blue: 195/255, opacity: 1) 
        public let androidColorlimeLime50 = Color(.sRGB, red: 249/255, green: 251/255, blue: 231/255, opacity: 1) 

        // cyan
        public let androidColorcyanCyan900 = Color(.sRGB, red: 0/255, green: 96/255, blue: 100/255, opacity: 1) 
        public let androidColorcyanCyan800 = Color(.sRGB, red: 0/255, green: 131/255, blue: 143/255, opacity: 1) 
        public let androidColorcyanCyan700 = Color(.sRGB, red: 0/255, green: 151/255, blue: 167/255, opacity: 1) 
        public let androidColorcyanCyan600 = Color(.sRGB, red: 0/255, green: 172/255, blue: 193/255, opacity: 1) 
        public let androidColorcyanCyan500 = Color(.sRGB, red: 0/255, green: 188/255, blue: 212/255, opacity: 1) 
        public let androidColorcyanCyan400 = Color(.sRGB, red: 38/255, green: 198/255, blue: 218/255, opacity: 1) 
        public let androidColorcyanCyan300 = Color(.sRGB, red: 77/255, green: 208/255, blue: 225/255, opacity: 1) 
        public let androidColorcyanCyan200 = Color(.sRGB, red: 128/255, green: 222/255, blue: 234/255, opacity: 1) 
        public let androidColorcyanCyan100 = Color(.sRGB, red: 178/255, green: 235/255, blue: 242/255, opacity: 1) 
        public let androidColorcyanCyan50 = Color(.sRGB, red: 224/255, green: 247/255, blue: 250/255, opacity: 1) 

        // purple
        public let androidColorpurplePurple900 = Color(.sRGB, red: 74/255, green: 20/255, blue: 140/255, opacity: 1) 
        public let androidColorpurplePurple800 = Color(.sRGB, red: 106/255, green: 27/255, blue: 154/255, opacity: 1) 
        public let androidColorpurplePurple700 = Color(.sRGB, red: 123/255, green: 31/255, blue: 162/255, opacity: 1) 
        public let androidColorpurplePurple600 = Color(.sRGB, red: 142/255, green: 36/255, blue: 170/255, opacity: 1) 
        public let androidColorpurplePurple500 = Color(.sRGB, red: 156/255, green: 39/255, blue: 176/255, opacity: 1) 
        public let androidColorpurplePurple400 = Color(.sRGB, red: 171/255, green: 71/255, blue: 188/255, opacity: 1) 
        public let androidColorpurplePurple300 = Color(.sRGB, red: 186/255, green: 104/255, blue: 200/255, opacity: 1) 
        public let androidColorpurplePurple200 = Color(.sRGB, red: 206/255, green: 147/255, blue: 216/255, opacity: 1) 
        public let androidColorpurplePurple100 = Color(.sRGB, red: 225/255, green: 190/255, blue: 231/255, opacity: 1) 
        public let androidColorpurplePurple50 = Color(.sRGB, red: 243/255, green: 229/255, blue: 245/255, opacity: 1) 

        // blue gray
        public let androidColorblueGrayBlueGray900 = Color(.sRGB, red: 38/255, green: 50/255, blue: 56/255, opacity: 1) 
        public let androidColorblueGrayBlueGray800 = Color(.sRGB, red: 55/255, green: 71/255, blue: 79/255, opacity: 1) 
        public let androidColorblueGrayBlueGray700 = Color(.sRGB, red: 69/255, green: 90/255, blue: 100/255, opacity: 1) 
        public let androidColorblueGrayBlueGray600 = Color(.sRGB, red: 84/255, green: 110/255, blue: 122/255, opacity: 1) 
        public let androidColorblueGrayBlueGray500 = Color(.sRGB, red: 96/255, green: 125/255, blue: 139/255, opacity: 1) 
        public let androidColorblueGrayBlueGray400 = Color(.sRGB, red: 120/255, green: 144/255, blue: 156/255, opacity: 1) 
        public let androidColorblueGrayBlueGray300 = Color(.sRGB, red: 144/255, green: 164/255, blue: 174/255, opacity: 1) 
        public let androidColorblueGrayBlueGray200 = Color(.sRGB, red: 176/255, green: 190/255, blue: 197/255, opacity: 1) 
        public let androidColorblueGrayBlueGray100 = Color(.sRGB, red: 207/255, green: 216/255, blue: 220/255, opacity: 1) 
        public let androidColorblueGrayBlueGray50 = Color(.sRGB, red: 236/255, green: 239/255, blue: 241/255, opacity: 1) 

        // gray
        public let androidColorgrayGray900 = Color(.sRGB, red: 33/255, green: 33/255, blue: 33/255, opacity: 1) 
        public let androidColorgrayGray800 = Color(.sRGB, red: 66/255, green: 66/255, blue: 66/255, opacity: 1) 
        public let androidColorgrayGray700 = Color(.sRGB, red: 97/255, green: 97/255, blue: 97/255, opacity: 1) 
        public let androidColorgrayGray600 = Color(.sRGB, red: 117/255, green: 117/255, blue: 117/255, opacity: 1) 
        public let androidColorgrayGray500 = Color(.sRGB, red: 158/255, green: 158/255, blue: 158/255, opacity: 1) 
        public let androidColorgrayGray400 = Color(.sRGB, red: 189/255, green: 189/255, blue: 189/255, opacity: 1) 
        public let androidColorgrayGray300 = Color(.sRGB, red: 224/255, green: 224/255, blue: 224/255, opacity: 1) 
        public let androidColorgrayGray200 = Color(.sRGB, red: 238/255, green: 238/255, blue: 238/255, opacity: 1) 
        public let androidColorgrayGray100 = Color(.sRGB, red: 245/255, green: 245/255, blue: 245/255, opacity: 1) 
        public let androidColorgrayGray50 = Color(.sRGB, red: 250/255, green: 250/255, blue: 250/255, opacity: 1) 
        public let androidColorgrayBlack = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let androidColorgrayWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // deep purple
        public let androidColordeepPurpleDeepPurple900 = Color(.sRGB, red: 49/255, green: 27/255, blue: 146/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple800 = Color(.sRGB, red: 69/255, green: 39/255, blue: 160/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple700 = Color(.sRGB, red: 81/255, green: 45/255, blue: 168/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple600 = Color(.sRGB, red: 94/255, green: 53/255, blue: 177/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple500 = Color(.sRGB, red: 103/255, green: 58/255, blue: 183/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple400 = Color(.sRGB, red: 126/255, green: 87/255, blue: 194/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple300 = Color(.sRGB, red: 149/255, green: 117/255, blue: 205/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple200 = Color(.sRGB, red: 179/255, green: 157/255, blue: 219/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple100 = Color(.sRGB, red: 209/255, green: 196/255, blue: 233/255, opacity: 1) 
        public let androidColordeepPurpleDeepPurple50 = Color(.sRGB, red: 237/255, green: 231/255, blue: 246/255, opacity: 1) 

        // yellow
        public let androidColoryellowYellow900 = Color(.sRGB, red: 245/255, green: 127/255, blue: 23/255, opacity: 1) 
        public let androidColoryellowYellow800 = Color(.sRGB, red: 249/255, green: 168/255, blue: 37/255, opacity: 1) 
        public let androidColoryellowYellow700 = Color(.sRGB, red: 251/255, green: 192/255, blue: 45/255, opacity: 1) 
        public let androidColoryellowYellow600 = Color(.sRGB, red: 253/255, green: 216/255, blue: 53/255, opacity: 1) 
        public let androidColoryellowYellow500 = Color(.sRGB, red: 255/255, green: 235/255, blue: 59/255, opacity: 1) 
        public let androidColoryellowYellow400 = Color(.sRGB, red: 255/255, green: 238/255, blue: 88/255, opacity: 1) 
        public let androidColoryellowYellow300 = Color(.sRGB, red: 255/255, green: 241/255, blue: 118/255, opacity: 1) 
        public let androidColoryellowYellow200 = Color(.sRGB, red: 255/255, green: 245/255, blue: 157/255, opacity: 1) 
        public let androidColoryellowYellow100 = Color(.sRGB, red: 255/255, green: 249/255, blue: 196/255, opacity: 1) 
        public let androidColoryellowYellow50 = Color(.sRGB, red: 255/255, green: 253/255, blue: 231/255, opacity: 1) 

        // indigo
        public let androidColorindigoIndigo900 = Color(.sRGB, red: 26/255, green: 35/255, blue: 126/255, opacity: 1) 
        public let androidColorindigoIndigo800 = Color(.sRGB, red: 40/255, green: 53/255, blue: 147/255, opacity: 1) 
        public let androidColorindigoIndigo700 = Color(.sRGB, red: 48/255, green: 63/255, blue: 159/255, opacity: 1) 
        public let androidColorindigoIndigo600 = Color(.sRGB, red: 57/255, green: 73/255, blue: 171/255, opacity: 1) 
        public let androidColorindigoIndigo500 = Color(.sRGB, red: 63/255, green: 81/255, blue: 181/255, opacity: 1) 
        public let androidColorindigoIndigo400 = Color(.sRGB, red: 92/255, green: 107/255, blue: 192/255, opacity: 1) 
        public let androidColorindigoIndigo300 = Color(.sRGB, red: 121/255, green: 134/255, blue: 203/255, opacity: 1) 
        public let androidColorindigoIndigo200 = Color(.sRGB, red: 159/255, green: 168/255, blue: 218/255, opacity: 1) 
        public let androidColorindigoIndigo100 = Color(.sRGB, red: 197/255, green: 202/255, blue: 233/255, opacity: 1) 
        public let androidColorindigoIndigo50 = Color(.sRGB, red: 232/255, green: 234/255, blue: 246/255, opacity: 1) 

        // green
        public let androidColorgreenGreen900 = Color(.sRGB, red: 27/255, green: 94/255, blue: 32/255, opacity: 1) 
        public let androidColorgreenGreen800 = Color(.sRGB, red: 46/255, green: 125/255, blue: 50/255, opacity: 1) 
        public let androidColorgreenGreen700 = Color(.sRGB, red: 56/255, green: 142/255, blue: 60/255, opacity: 1) 
        public let androidColorgreenGreen600 = Color(.sRGB, red: 67/255, green: 160/255, blue: 71/255, opacity: 1) 
        public let androidColorgreenGreen500 = Color(.sRGB, red: 76/255, green: 175/255, blue: 80/255, opacity: 1) 
        public let androidColorgreenGreen400 = Color(.sRGB, red: 102/255, green: 187/255, blue: 106/255, opacity: 1) 
        public let androidColorgreenGreen300 = Color(.sRGB, red: 129/255, green: 199/255, blue: 132/255, opacity: 1) 
        public let androidColorgreenGreen200 = Color(.sRGB, red: 165/255, green: 214/255, blue: 167/255, opacity: 1) 
        public let androidColorgreenGreen100 = Color(.sRGB, red: 200/255, green: 230/255, blue: 201/255, opacity: 1) 
        public let androidColorgreenGreen50 = Color(.sRGB, red: 232/255, green: 245/255, blue: 233/255, opacity: 1) 

        // amber
        public let androidColoramberAmber900 = Color(.sRGB, red: 255/255, green: 111/255, blue: 0/255, opacity: 1) 
        public let androidColoramberAmber800 = Color(.sRGB, red: 255/255, green: 143/255, blue: 0/255, opacity: 1) 
        public let androidColoramberAmber700 = Color(.sRGB, red: 255/255, green: 160/255, blue: 0/255, opacity: 1) 
        public let androidColoramberAmber600 = Color(.sRGB, red: 255/255, green: 179/255, blue: 0/255, opacity: 1) 
        public let androidColoramberAmber500 = Color(.sRGB, red: 255/255, green: 193/255, blue: 7/255, opacity: 1) 
        public let androidColoramberAmber400 = Color(.sRGB, red: 255/255, green: 202/255, blue: 40/255, opacity: 1) 
        public let androidColoramberAmber300 = Color(.sRGB, red: 255/255, green: 213/255, blue: 79/255, opacity: 1) 
        public let androidColoramberAmber200 = Color(.sRGB, red: 255/255, green: 224/255, blue: 130/255, opacity: 1) 
        public let androidColoramberAmber100 = Color(.sRGB, red: 255/255, green: 236/255, blue: 179/255, opacity: 1) 
        public let androidColoramberAmber50 = Color(.sRGB, red: 255/255, green: 248/255, blue: 225/255, opacity: 1) 

        // light green
        public let androidColorlightGreenLightGreen900 = Color(.sRGB, red: 51/255, green: 105/255, blue: 30/255, opacity: 1) 
        public let androidColorlightGreenLightGreen800 = Color(.sRGB, red: 85/255, green: 139/255, blue: 47/255, opacity: 1) 
        public let androidColorlightGreenLightGreen700 = Color(.sRGB, red: 104/255, green: 159/255, blue: 56/255, opacity: 1) 
        public let androidColorlightGreenLightGreen600 = Color(.sRGB, red: 124/255, green: 179/255, blue: 66/255, opacity: 1) 
        public let androidColorlightGreenLightGreen500 = Color(.sRGB, red: 139/255, green: 195/255, blue: 74/255, opacity: 1) 
        public let androidColorlightGreenLightGreen400 = Color(.sRGB, red: 156/255, green: 204/255, blue: 101/255, opacity: 1) 
        public let androidColorlightGreenLightGreen300 = Color(.sRGB, red: 174/255, green: 213/255, blue: 129/255, opacity: 1) 
        public let androidColorlightGreenLightGreen200 = Color(.sRGB, red: 197/255, green: 225/255, blue: 165/255, opacity: 1) 
        public let androidColorlightGreenLightGreen100 = Color(.sRGB, red: 220/255, green: 237/255, blue: 200/255, opacity: 1) 
        public let androidColorlightGreenLightGreen50 = Color(.sRGB, red: 241/255, green: 248/255, blue: 233/255, opacity: 1) 

        // blue
        public let androidColorblueBlue900 = Color(.sRGB, red: 13/255, green: 71/255, blue: 161/255, opacity: 1) 
        public let androidColorblueBlue800 = Color(.sRGB, red: 21/255, green: 101/255, blue: 192/255, opacity: 1) 
        public let androidColorblueBlue700 = Color(.sRGB, red: 25/255, green: 118/255, blue: 210/255, opacity: 1) 
        public let androidColorblueBlue600 = Color(.sRGB, red: 30/255, green: 136/255, blue: 229/255, opacity: 1) 
        public let androidColorblueBlue500 = Color(.sRGB, red: 33/255, green: 150/255, blue: 243/255, opacity: 1) 
        public let androidColorblueBlue400 = Color(.sRGB, red: 66/255, green: 165/255, blue: 245/255, opacity: 1) 
        public let androidColorblueBlue300 = Color(.sRGB, red: 100/255, green: 181/255, blue: 246/255, opacity: 1) 
        public let androidColorblueBlue200 = Color(.sRGB, red: 144/255, green: 202/255, blue: 249/255, opacity: 1) 
        public let androidColorblueBlue100 = Color(.sRGB, red: 187/255, green: 222/255, blue: 251/255, opacity: 1) 
        public let androidColorblueBlue50 = Color(.sRGB, red: 227/255, green: 242/255, blue: 253/255, opacity: 1) 

        // brown
        public let androidColorbrownBrown900 = Color(.sRGB, red: 62/255, green: 39/255, blue: 35/255, opacity: 1) 
        public let androidColorbrownBrown800 = Color(.sRGB, red: 78/255, green: 52/255, blue: 46/255, opacity: 1) 
        public let androidColorbrownBrown700 = Color(.sRGB, red: 93/255, green: 64/255, blue: 55/255, opacity: 1) 
        public let androidColorbrownBrown600 = Color(.sRGB, red: 109/255, green: 76/255, blue: 65/255, opacity: 1) 
        public let androidColorbrownBrown500 = Color(.sRGB, red: 121/255, green: 85/255, blue: 72/255, opacity: 1) 
        public let androidColorbrownBrown400 = Color(.sRGB, red: 141/255, green: 110/255, blue: 99/255, opacity: 1) 
        public let androidColorbrownBrown300 = Color(.sRGB, red: 161/255, green: 136/255, blue: 127/255, opacity: 1) 
        public let androidColorbrownBrown200 = Color(.sRGB, red: 188/255, green: 170/255, blue: 164/255, opacity: 1) 
        public let androidColorbrownBrown100 = Color(.sRGB, red: 215/255, green: 204/255, blue: 200/255, opacity: 1) 
        public let androidColorbrownBrown50 = Color(.sRGB, red: 239/255, green: 235/255, blue: 233/255, opacity: 1) 

        // deep orange
        public let androidColordeepOrangeDeepOrange900 = Color(.sRGB, red: 191/255, green: 54/255, blue: 12/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange800 = Color(.sRGB, red: 216/255, green: 67/255, blue: 21/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange700 = Color(.sRGB, red: 230/255, green: 74/255, blue: 25/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange600 = Color(.sRGB, red: 244/255, green: 81/255, blue: 30/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange500 = Color(.sRGB, red: 255/255, green: 87/255, blue: 34/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange400 = Color(.sRGB, red: 255/255, green: 112/255, blue: 67/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange300 = Color(.sRGB, red: 255/255, green: 138/255, blue: 101/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange200 = Color(.sRGB, red: 255/255, green: 171/255, blue: 145/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange100 = Color(.sRGB, red: 255/255, green: 204/255, blue: 188/255, opacity: 1) 
        public let androidColordeepOrangeDeepOrange50 = Color(.sRGB, red: 251/255, green: 233/255, blue: 231/255, opacity: 1) 

        // orange
        public let androidColororangeOrange900 = Color(.sRGB, red: 230/255, green: 81/255, blue: 0/255, opacity: 1) 
        public let androidColororangeOrange800 = Color(.sRGB, red: 239/255, green: 108/255, blue: 0/255, opacity: 1) 
        public let androidColororangeOrange700 = Color(.sRGB, red: 245/255, green: 124/255, blue: 0/255, opacity: 1) 
        public let androidColororangeOrange600 = Color(.sRGB, red: 251/255, green: 140/255, blue: 0/255, opacity: 1) 
        public let androidColororangeOrange500 = Color(.sRGB, red: 255/255, green: 152/255, blue: 0/255, opacity: 1) 
        public let androidColororangeOrange400 = Color(.sRGB, red: 255/255, green: 167/255, blue: 38/255, opacity: 1) 
        public let androidColororangeOrange300 = Color(.sRGB, red: 255/255, green: 183/255, blue: 77/255, opacity: 1) 
        public let androidColororangeOrange200 = Color(.sRGB, red: 255/255, green: 204/255, blue: 128/255, opacity: 1) 
        public let androidColororangeOrange100 = Color(.sRGB, red: 255/255, green: 224/255, blue: 178/255, opacity: 1) 
        public let androidColororangeOrange50 = Color(.sRGB, red: 255/255, green: 243/255, blue: 224/255, opacity: 1) 

        // red
        public let androidColorredRed900 = Color(.sRGB, red: 183/255, green: 28/255, blue: 28/255, opacity: 1) 
        public let androidColorredRed800 = Color(.sRGB, red: 198/255, green: 40/255, blue: 40/255, opacity: 1) 
        public let androidColorredRed700 = Color(.sRGB, red: 211/255, green: 47/255, blue: 47/255, opacity: 1) 
        public let androidColorredRed600 = Color(.sRGB, red: 229/255, green: 57/255, blue: 53/255, opacity: 1) 
        public let androidColorredRed500 = Color(.sRGB, red: 244/255, green: 67/255, blue: 54/255, opacity: 1) 
        public let androidColorredRed400 = Color(.sRGB, red: 239/255, green: 83/255, blue: 80/255, opacity: 1) 
        public let androidColorredRed300 = Color(.sRGB, red: 229/255, green: 115/255, blue: 115/255, opacity: 1) 
        public let androidColorredRed200 = Color(.sRGB, red: 239/255, green: 154/255, blue: 154/255, opacity: 1) 
        public let androidColorredRed100 = Color(.sRGB, red: 255/255, green: 205/255, blue: 210/255, opacity: 1) 
        public let androidColorredRed50 = Color(.sRGB, red: 255/255, green: 235/255, blue: 238/255, opacity: 1) 

        // pink
        public let androidColorpinkPink900 = Color(.sRGB, red: 136/255, green: 14/255, blue: 79/255, opacity: 1) 
        public let androidColorpinkPink800 = Color(.sRGB, red: 173/255, green: 20/255, blue: 87/255, opacity: 1) 
        public let androidColorpinkPink700 = Color(.sRGB, red: 194/255, green: 24/255, blue: 91/255, opacity: 1) 
        public let androidColorpinkPink600 = Color(.sRGB, red: 216/255, green: 27/255, blue: 96/255, opacity: 1) 
        public let androidColorpinkPink500 = Color(.sRGB, red: 233/255, green: 30/255, blue: 99/255, opacity: 1) 
        public let androidColorpinkPink400 = Color(.sRGB, red: 236/255, green: 64/255, blue: 122/255, opacity: 1) 
        public let androidColorpinkPink300 = Color(.sRGB, red: 240/255, green: 98/255, blue: 146/255, opacity: 1) 
        public let androidColorpinkPink200 = Color(.sRGB, red: 244/255, green: 143/255, blue: 177/255, opacity: 1) 
        public let androidColorpinkPink100 = Color(.sRGB, red: 248/255, green: 187/255, blue: 208/255, opacity: 1) 
        public let androidColorpinkPink50 = Color(.sRGB, red: 252/255, green: 228/255, blue: 236/255, opacity: 1) 

        // background
        public let backgroundSurfacePrimary = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let backgroundSurfaceSecondary = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // button

        // Primary
        public let buttonPrimaryButtonPrimaryStandardBackgroundColor = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let buttonPrimaryButtonPrimaryHoverBackgroundColor = Color(.sRGB, red: 118/255, green: 48/255, blue: 247/255, opacity: 1) 
        public let buttonPrimaryButtonPrimaryPressedBackgroundColor = Color(.sRGB, red: 104/255, green: 30/255, blue: 227/255, opacity: 1) 
        public let buttonPrimaryButtonPrimaryDisabledBackgroundColor = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let buttonPrimaryButtonPrimaryDisabledTextColor = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let buttonPrimaryButtonPrimaryTextColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // Secondary
        public let buttonSecondaryButtonSecondaryStandardBackgroundColor = Color(.sRGB, red: 236/255, green: 232/255, blue: 255/255, opacity: 1) 
        public let buttonSecondaryButtonSecondaryHoverBackgroundColor = Color(.sRGB, red: 218/255, green: 212/255, blue: 255/255, opacity: 1) 
        public let buttonSecondaryButtonSecondaryPressedBackgroundColor = Color(.sRGB, red: 218/255, green: 212/255, blue: 255/255, opacity: 1) 
        public let buttonSecondaryButtonSecondaryDisabledTextColor = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let buttonSecondaryButtonSecondaryDisabledBackgroundColor = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let buttonSecondaryButtonSecondaryTextColor = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 

        // Tertiary
        public let buttonTertiaryButtonTertiaryStandardBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let buttonTertiaryButtonTertiaryStandardBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let buttonTertiaryButtonTertiaryTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let buttonTertiaryButtonTertiaryHoverBackgroundColor = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let buttonTertiaryButtonTertiaryPressedBackgroundColor = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let buttonTertiaryButtonTertiaryDisabledBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let buttonTertiaryButtonTertiaryDisabledTextColor = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 

        // Ghost
        public let buttonGhostButtonGhostStandardTextColor = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let buttonGhostButtonGhostHoverTextColor = Color(.sRGB, red: 118/255, green: 48/255, blue: 247/255, opacity: 1) 
        public let buttonGhostButtonGhostPressedTextColor = Color(.sRGB, red: 104/255, green: 30/255, blue: 227/255, opacity: 1) 
        public let buttonGhostButtonGhostDisabledTextColor = Color(.sRGB, red: 218/255, green: 212/255, blue: 255/255, opacity: 1) 

        // pagination
        public let paginationPaginationBackgroudColor1 = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let paginationPaginationBackgroudColor2 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // bottom navigation
        public let bottomNavigationBottomNavigationBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let bottomNavigationBottomNavigationBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let bottomNavigationBottomNavigationSelectedColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let bottomNavigationBottomNavigationDeselectedColor = Color(.sRGB, red: 148/255, green: 163/255, blue: 184/255, opacity: 1) 
        public let bottomNavigationBottomNavigationIndicatorColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 

        // coach mark
        public let coachMarkCoachMarkBackgroundColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let coachMarkCoachMarkTextColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // notification badge
        public let notificationBadgeBadgeBackgroundColor = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let notificationBadgeBadgeTextColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let notificationBadgeBadgeBorderColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // ios home indicator
        public let iosHomeIndicatorIndicatorColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosHomeIndicatorBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // android home indicator
        public let androidHomeIndicatorIndicatorColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let androidHomeIndicatorBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // alert
        public let alertAlertBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let alertAlertTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let alertAlertBorderColor = Color(.sRGB, red: 226/255, green: 226/255, blue: 226/255, opacity: 1) 

        // ios alert
        public let iosAlertAlertBackgroundColor = Color(.sRGB, red: 242/255, green: 242/255, blue: 242/255, opacity: 0.82) 
        public let iosAlertAlertBorderColor = Color(.sRGB, red: 60/255, green: 60/255, blue: 67/255, opacity: 0.36) 
        public let iosAlertAlertTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosAlertAlertHighlightColor = Color(.sRGB, red: 0/255, green: 122/255, blue: 255/255, opacity: 1) 
        public let iosAlertAlertInputColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // android alert
        public let androidAlertAlertBackgroundColor = Color(.sRGB, red: 238/255, green: 238/255, blue: 238/255, opacity: 1) 
        public let androidAlertAlertPrimaryTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let androidAlertAlertSecondaryTextColor = Color(.sRGB, red: 97/255, green: 97/255, blue: 97/255, opacity: 1) 

        // menu
        public let menuMenuBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let menuMenuBorderColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let menuMenuTextColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let menuMenuIconColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // input field
        public let inputFieldTextFieldBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let inputFieldTextFieldBorderStandardColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let inputFieldTextFieldBorderHoverColor = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let inputFieldTextFieldBorderPressedColor = Color(.sRGB, red: 148/255, green: 163/255, blue: 184/255, opacity: 1) 
        public let inputFieldTextFieldTextColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let inputFieldTextFieldTextInputColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let inputFieldSearchFieldBackgroundColor = Color(.sRGB, red: 248/255, green: 250/255, blue: 252/255, opacity: 1) 
        public let inputFieldSearchFieldBackgroundHoverColor = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let inputFieldSearchFieldBackgroundPressedColor = Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1) 
        public let inputFieldSearchFieldTextColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let inputFieldErrorFieldBorderColor = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let inputFieldErrorFieldTextColor = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let inputFieldErrorFieldInputColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let inputFieldSuccessFieldBorderColor = Color(.sRGB, red: 0/255, green: 181/255, blue: 5/255, opacity: 1) 
        public let inputFieldSuccessFieldTextColor = Color(.sRGB, red: 0/255, green: 181/255, blue: 5/255, opacity: 1) 
        public let inputFieldSuccessFieldInputColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let inputFieldDisabledFieldTextColor = Color(.sRGB, red: 203/255, green: 213/255, blue: 225/255, opacity: 1) 
        public let inputFieldDisabledFieldIconColor = Color(.sRGB, red: 255/255, green: 214/255, blue: 0/255, opacity: 1) 

        // bottom sheet
        public let bottomSheetBottomSheetBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let bottomSheetBottomSheetIndicatorColor = Color(.sRGB, red: 226/255, green: 232/255, blue: 240/255, opacity: 1) 
        public let bottomSheetBottomSheetTitleColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let bottomSheetBottomSheetTextColor = Color(.sRGB, red: 100/255, green: 116/255, blue: 139/255, opacity: 1) 
        public let bottomSheetBottomSheetIconColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 

        // ios bottom sheet
        public let iosBottomSheetBottomSheetBackgroundColor = Color(.sRGB, red: 242/255, green: 242/255, blue: 242/255, opacity: 0.82) 
        public let iosBottomSheetBottomSheetTextColor = Color(.sRGB, red: 123/255, green: 123/255, blue: 128/255, opacity: 1) 
        public let iosBottomSheetBottomSheetBorderColor = Color(.sRGB, red: 60/255, green: 60/255, blue: 67/255, opacity: 0.36) 
        public let iosBottomSheetBottomSheetOptionColor = Color(.sRGB, red: 0/255, green: 122/255, blue: 255/255, opacity: 1) 
        public let iosBottomSheetBottomSheetErrorColor = Color(.sRGB, red: 255/255, green: 59/255, blue: 48/255, opacity: 1) 

        // ios share sheet
        public let iosShareSheetShareSheetBackgroundColor = Color(.sRGB, red: 242/255, green: 242/255, blue: 242/255, opacity: 0.82) 
        public let iosShareSheetShareSheetBorderColor = Color(.sRGB, red: 60/255, green: 60/255, blue: 67/255, opacity: 0.36) 
        public let iosShareSheetShareSheetTitleColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosShareSheetShareSheetTextColor = Color(.sRGB, red: 60/255, green: 60/255, blue: 67/255, opacity: 0.6) 
        public let iosShareSheetShareSheetIconColor = Color(.sRGB, red: 118/255, green: 118/255, blue: 128/255, opacity: 0.12) 
        public let iosShareSheetShareSheetBoxColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // android bottom sheet
        public let androidBottomSheetBottomSheetBackgroundColor = Color(.sRGB, red: 243/255, green: 237/255, blue: 247/255, opacity: 1) 
        public let androidBottomSheetBottomSheetTextColor = Color(.sRGB, red: 29/255, green: 27/255, blue: 32/255, opacity: 1) 
        public let androidBottomSheetBottomSheetIconColor = Color(.sRGB, red: 73/255, green: 69/255, blue: 79/255, opacity: 1) 

        // badge
        public let badgeBadgeDefaultBackgroundColor = Color(.sRGB, red: 2/255, green: 6/255, blue: 23/255, opacity: 1) 
        public let badgeBadgeSuccessBackgroundColor = Color(.sRGB, red: 0/255, green: 221/255, blue: 0/255, opacity: 1) 
        public let badgeBadgeErrorBackgroundColor = Color(.sRGB, red: 255/255, green: 44/255, blue: 32/255, opacity: 1) 
        public let badgeBadgeNewBackgroundColor = Color(.sRGB, red: 126/255, green: 73/255, blue: 255/255, opacity: 1) 
        public let badgeBadgeTextColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // ios status bar
        public let iosStatusBarStatusBarTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosStatusBarStatusBarBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // android status bar
        public let androidStatusBarStatusBarTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let androidStatusBarStatusBarBackgroundColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // ios keyboard
        public let iosKeyboardKeyboardBackgroundColor = Color(.sRGB, red: 206/255, green: 208/255, blue: 212/255, opacity: 1) 
        public let iosKeyboardKeyboardTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let iosKeyboardKeyboardLetterColor = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let iosKeyboardKeyboardIconColor = Color(.sRGB, red: 80/255, green: 85/255, blue: 92/255, opacity: 1) 
        public let iosKeyboardKeyboardBigLetterColor = Color(.sRGB, red: 171/255, green: 176/255, blue: 186/255, opacity: 1) 
        public let iosKeyboardKeyboardShadowColor = Color(.sRGB, red: 137/255, green: 138/255, blue: 141/255, opacity: 1) 

        // android keyboard
        public let androidKeyboardKeyboardBackgroundColor = Color(.sRGB, red: 254/255, green: 247/255, blue: 255/255, opacity: 1) 
        public let androidKeyboardKeyboardLetterColor = Color(.sRGB, red: 247/255, green: 242/255, blue: 250/255, opacity: 1) 
        public let androidKeyboardKeyboardTextColor = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let androidKeyboardKeyboardBackColor = Color(.sRGB, red: 208/255, green: 188/255, blue: 255/255, opacity: 1) 
        public let androidKeyboardKeyboardBigLetterColor = Color(.sRGB, red: 230/255, green: 224/255, blue: 233/255, opacity: 1) 
        public let androidKeyboardKeyboardBorderColor = Color(.sRGB, red: 158/255, green: 158/255, blue: 158/255, opacity: 1) 
    }
}