import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    // Shadow

    func shadowShadowS() -> some View {
        return self.shadow(color: Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1), radius: 4, x: 0, y: 4) 
    }

    func shadowShadowM() -> some View {
        return self.shadow(color: Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1), radius: 8, x: 0, y: 8) 
    }

    func shadowShadowL() -> some View {
        return self.shadow(color: Color(.sRGB, red: 241/255, green: 245/255, blue: 249/255, opacity: 1), radius: 16, x: 0, y: 16) 
    }
}